### ISSUE TITLE
Instructions to run in an end to end manner

### ISSUE THREAD

**Issue by siddharthsrivastava** [gjovanov/roomler#1]
Hi

Do you have instructions on how to proceed completing the setup ?
For example,  How to create the user in mongodb via docker

If you can provide some details on how to manage things from end-to-end, it will help a lot.

**Comment by gjovanov** [comment]
Hi @siddharthsrivastava,
Most of the instructions can be found either in the main README or on Medium:

https://medium.com/@gjovanov/building-your-own-slack-54874bf5fd7a

The quick and dirty way to start mongo as a docker service, is by running:
`docker run -d --name mongo --restart=always -p 27017:27017 -v mongo_data:/data/db mongo`

Notice that this will create without username and password (recommended only for your development environment - NOT FOR PRODUCTION).

Also can start the container with admin account:
```docker
docker run --name mongo \
	-e MONGO_INITDB_ROOT_USERNAME=SuperUser \
	-e MONGO_INITDB_ROOT_PASSWORD=SuperSecret \
	-p 1212:27017 \
        -v mongo_data:/data/db
```

then you can connect to the admin DB via the terminal/bash/CMD:

`mongo admin -u SuperUser -p SuperSecret --host localhost --port 27017`

once logged in:
```javascript
use roomlerdb
db.createUser(
  {
    user: "roomler_user",
    pwd: "super_secret",
    roles: [ { role: "readWrite", db: "roomlerdb" } ]
  }
)
```

Another way to start the whole stack is via `dockerc-compose`:

https://github.com/gjovanov/roomler/blob/master/docker-compose.yml

`docker-compose up`

Before doing that, you need to create your `.env` file with all the environment variables needed in that file... e.g:
```
MONGO_INITDB_ROOT_USERNAME=YOUR_MONGO_ROOT_USER
TURN_USERNAME=YOUR_TURN_USER
etc...
```

In case you run the `mongo` without authentication (no admin account), then you can omit the env variable DB_URL with will default to: `mongodb://localhost:27017/roomdb`

Otherwise you need to put username and password in the connection string:
`DB_CONN=mongodb://roomler_user:super_secret@mongo/roomlerdb`

Let me know if you encounter any specific issue.

**Comment by gjovanov** [comment]
@siddharthsrivastava  any update on this one or we can close it?

**Comment by siddharthsrivastava** [comment]
> @siddharthsrivastava any update on this one or we can close it?

Yes, can be closed. Thank you
