### ISSUE TITLE
MongoDB for ubuntu 32-bit

### ISSUE THREAD

**Issue by homevk15** [gjovanov/roomler#2]
Have a good day!
I have installed MongoDB in ubuntu 18.04 (32 bit) according to the next instruction
https://dzone.com/articles/installing-mongodb-on-32-bit-ubuntu-1510
Please, help me, how I should change "docker" to get Roomler worked
docker run -d --name mongo \ --restart=always \ -p 27017:27017 \ -v mongo_data:/data/db \ 
mongo 
attach mongo container to backend network 
docker network connect backend mongo
because this works only for 64 bit
Thank you in advance!

**Comment by gjovanov** [comment]
Hey @homevk15,
if you have x64 bit machine, then it's recommended you install x64 apps/services.

As for mongo, yes you can install it on `bare metal`, but for more flexibility in upgrading to newer versions of mongo, i recommend you install it via `docker`.

For that you need to install latest docker e.g.:
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04

Also pls make sure you understand basics of docker.

Pls make sure that you install all services on by one (mongo, redis, coturn, janus, ...). Other option is to start them all at once via `docker-compose`, but this is way too advance way of doing it and it's better that you first start with the most simple approach.

**Comment by homevk15** [comment]
thank you for reply.
if I don't have x64 bit machine then there is not way to install MongoDB and use docker for it? 
New releases of MongoDB are not used for x32 bit more.

**Comment by gjovanov** [comment]
hi @homevk15 ,
in general i don't have the experience with installing mongodb on x32 bit machines and since you say that newest mongo versions are not being compiled to x32 architectures, then I also doubt that docker will help for that.

I suggest, you consider some of the cheaper hosting providers for dedicated machines e.g. Hetzner:

https://www.hetzner.de/dedicated-rootserver/matrix-ex

btw, I'm not affiliated with them in any manner. I just know they are providing good quality bare metal servers for a relatively affordable price.  So this kind of option might be something that you can consider as well.

**Comment by gjovanov** [comment]
Hey @homevk15 , since this is not a Roomler related issue, I'm closing it... Feel free to reopen in case of an issue with roomler.
