### ISSUE TITLE
nginx error

### ISSUE THREAD

**Issue by homevk15** [gjovanov/roomler#3]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/your_path/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/0f5b64727f6fc7169d6ae98b5ce33aefb788ed1d34ec200ee570ea63e06e30e3/merged\\\" at \\\"/var/lib/docker/overlay2/0f5b64727f6fc7169d6ae98b5ce33aefb788ed1d34ec200ee570ea63e06e30e3/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
==========================================
Error response from daemon: container sharing network namespace with another container or host cannot be connected to any other network

**Comment by gjovanov** [comment]
Hey @homevk15,
pls don't post large error logs for reporting issues, but use pastebin or gist or similar services instead.

Also you need provide more details, what command exactly did you tried running?

To me it seems that you used `your_path/nginx.conf` which only a place holder for your real folder on your HOST server where you have stored the `nginx.conf`.

Keep in mind that to run `roomler` a basic knowledge of docker is prerequisite.

I suggest you read a bit about `docker volume`s and docker in general, because without basic docker knowledge, it's hard to setup and run roomler. And teaching basics about `docker` is outside of scope of this repo.



/GJ

**Comment by gjovanov** [comment]
Hey @homevk15 , since this is not a Roomler related issue, I'm closing it... Feel free to reopen in case of an issue with roomler.

**Comment by isundaniyal** [comment]
but we can use -v to mount nginx.conf file ... it's detected as directory...
