### ISSUE TITLE
How many participants roomler can support in single session?

### ISSUE THREAD

**Issue by chiragmewada** [gjovanov/roomler#6]

**Comment by gjovanov** [comment]
Hi @chiragmewada ,
since it is working in SFU mode, it really depends on the following params:

- client bandwidth & hardware (RAM, CPU/GPU)
- video resolution
- bitrate

We have managed to reach 50 active video publishers with:
- resolution= QQVGA - 160x120
- bitrate 64kbit

On decent hardware laptops (8GB ram, 4x Core) on 250MBit networks.

We might even go further, but for our use case that was enough.


Hope it helps.

**Comment by gjovanov** [comment]
Closing as this is not an issue. Feel free to open in case of any issue encountered.
