### ISSUE TITLE
Nginx change default port from 443 ?

### ISSUE THREAD

**Issue by alter-sachin** [gjovanov/roomler#7]
Hey
I have been trying to get this up and running on a google cloud instance.
Using the docker-compose up command

Nginx is giving me some trouble. I get the following error.

Recreating 257a9250cd8e_roomler_nginx_1 ... error

ERROR: for 257a9250cd8e_roomler_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint roomler_nginx_1 (16205a8e8218c786ace78057489b1aca6636afe19e4cc0a2ec963da3fb6a60d5): Error starting userland proxy: listen tcp 127.0.0.1:443: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint roomler_nginx_1 (16205a8e8218c786ace78057489b1aca6636afe19e4cc0a2ec963da3fb6a60d5): Error starting userland proxy: listen tcp 127.0.0.1:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

As you can see in the .env file i have defined ip1 and ip2  as 127.0.0.1

I have also checked that there is no process running on port 443 using netstat

Is there a specific way to change the port from 443 to others?

What should be the value of IP1 or IP2...

Moreover can you share on what platform you have hosted roomler.live ? I could adopt a similar infrastructure for I am looking to develop heavily ontop of this.

**Comment by gjovanov** [comment]
Hi @alter-sachin ,
the provided particular `docker-compose` example assumes that the machine you are trying to deploy Roomler has two public IPs (IP1 and IP2 have to be public IPs). The reason it makes that assumption is because this is the only way I've managed to setup both 443 being used for both UDP/TCP and HTTP proxying:

1. NXING1 doing HTTP proxying to the same physical server to 443 - for Roomler, Janus
2. NGINX2 doing UDP/TCP proxying to the same physical server to 443 - for Coturn

You don't have to do that. Your COTURN can be exposed directly on its default port 3478. The benefit of exposing COTURN on 443 is that it will avoid the pitfalls of Firewalls/Antiviruses that are not configured to support non-standard ports like 3478. So on the default port some highly secured networks like corporate ones might, the gathering ICE candidates might fail.

So you either need to have:
- a machine with two public IP addresses
- or remove the second NGINX2 instance from the docker-compose and expose COTURN on its default port 3478.

We are deploying it on on-premise servers on Hetzner.

Hope it helps and feel free to close the issue, if it was clarified, otherwise don't hesitate to ask further questions.

**Comment by alter-sachin** [comment]
Thank you for your response. I am closing this for now.

**Comment by Novienzi** [comment]
I try using 2 IP and still got this error. How about that?
